export const SUMMARY_ORDER = {
    Subfolder: 1,
    Subfolders: 1,
    'Sample Type': 2,
    'Sample Types': 2,
    Sample: 3,
    Samples: 3,
    'Assay Type': 4,
    'Assay Types': 4,
    'Assay run': 5,
    'Assay runs': 5,
    'Workflow job': 6,
    'Workflow jobs': 6,
    'Pick List': 7,
    'Pick Lists': 7,
    Notebook: 8,
    Notebooks: 8,
    'Notebook template': 9,
    'Notebook templates': 9,
    CellLine: 10,
    CellLines: 10,
    Compound: 11,
    Compounds: 11,
    Construct: 12,
    Constructs: 12,
    ExpressionSystem: 13,
    ExpressionSystems: 13,
    MolecularSpecies: 14,
    MoleculeSet: 15,
    MoleculeSets: 15,
    Molecule: 16,
    Molecules: 16,
    NucSequence: 17,
    NucSequences: 17,
    ProtSequence: 18,
    ProtSequences: 18,
    Vector: 19,
    Vectors: 19,
    Batch: 20,
    Batches: 20,
    Ingredient: 21,
    Ingredients: 21,
    Mixture: 22,
    Mixtures: 22,
    'Raw material': 23,
    'Raw materials': 23,
};
