module.exports = {
    stories: [
        '../src/stories/AddEntityButton.stories.tsx',
        '../src/stories/AssayDesignDeleteConfirmModal.stories.tsx',
        '../src/stories/AssayDesignerPanels.stories.tsx',
        '../src/stories/AssayImportPanels.stories.tsx',
        '../src/stories/AssayPicker.stories.tsx',
        '../src/stories/AssayPropertiesPanel.stories.tsx',
        '../src/stories/BatchPropertiesPanel.stories.tsx',
        '../src/stories/Cards.stories.tsx',
        '../src/stories/ColorIcon.stories.tsx',
        '../src/stories/ColorPickerInput.stories.tsx',
        '../src/stories/CreateUsersModal.stories.tsx',
        '../src/stories/DataClassDesigner.stories.tsx',
        '../src/stories/DatasetDesignerPanels.stories.tsx',
        '../src/stories/DetailEditing.stories.tsx',
        '../src/stories/DomainFieldsDisplay.stories.tsx',
        '../src/stories/DomainForm.stories.tsx',
        '../src/stories/EntityDeleteConfirmModal.stories.tsx',
        '../src/stories/EntityTypeDeleteConfirmModal.stories.tsx',
        '../src/stories/ExpandableContainer.stories.tsx',
        '../src/stories/FileTree.stories.tsx',
        '../src/stories/Grid.stories.tsx',
        '../src/stories/ImportWithRenameConfirmModal.stories.tsx',
        '../src/stories/LabelOverlay.stories.tsx',
        '../src/stories/OmniBox.stories.tsx',
        '../src/stories/Progress.stories.tsx',
        '../src/stories/SampleSetSummary.stories.tsx',
        '../src/stories/SearchResultCard.stories.tsx',
        '../src/stories/SearchResultsPanel.stories.tsx',
        '../src/stories/Section.stories.tsx',
        '../src/stories/ServerActivityList.stories.tsx',
        '../src/stories/SubMenuItem.stories.tsx',
        '../src/stories/TimelineView.stories.tsx',
        '../src/stories/ToggleButtons.stories.tsx',
        '../src/stories/UserDeleteConfirmModal.stories.tsx',
        '../src/stories/UserDetailHeader.stories.tsx',
        '../src/stories/WizardNavButtons.stories.tsx',
        // '../src/stories/**/*.stories.@(ts|tsx)'
    ],
    addons: [
        '@storybook/addon-essentials',
    ],
}
